### ISSUE TITLE
Public mention-bot doesn't seem to be leaving comments?

### ISSUE THREAD

**Issue by alex** [facebook/mention-bot#230]
Example: https://github.com/pyca/cryptography/pull/3779

I think it's been broken for a while, although without reviewing all our PRs I couldn't tell you exactly when.

(PS: mention-bot is really fantastic, thanks for building it and running a public one to support OSS!)

**Comment by brettcannon** [comment]
It's been at least a month if not longer. I actually just deactivated it for CPython since it's been down for so long and no one seems to have noticed other than me.

**Comment by alex** [comment]
You're not the only one! I miss it! :-)

**Comment by vjeux** [comment]
Oh noes :( Would anyone be interested in fixing it and putting it back up?

**Comment by alex** [comment]
@vjeux is that directed at the other mention-bot maintainers? I don't think those of us who are merely consumers of it have any way to know how it broke :-)

**Comment by vjeux** [comment]
You can run a local version via heroku and see what happens.

**Comment by rochacbruno** [comment]
Any of you deployed in heroku to see if it works? is that working?

**Comment by martinvw** [comment]
@vjeux it also fails for us for some time already, but heroku page looks happy:

```
GitHub Mention Bot Active. Go to https://github.com/facebook/mention-bot for more information.
```

Maybe the GitHub api changed?

**Comment by blueyed** [comment]
Also existing comments seem to have been deleted?!

**Comment by rallytime** [comment]
Mention bot was working for us, and has been for about 6 months, until a couple of days ago. (We are self-hosting, no changes to the bot recently.)

The payloads are being delivered to the bot just fine, and the bot receives them. Something is going wrong when the bot tries to analyze the reviewers:
```
Sep 26 12:56:00 autobots node[11328]: https://github.com/saltstack/salt/pull/43756
Sep 26 12:56:01 autobots node[11328]: Reviewers: []
Sep 26 12:56:01 autobots node[11328]: Skipping because there are no reviewers found.
```
This PR should have had reviewers ^^ and the bot hasn't been commenting on PRs since then. The last pull request that had reviewers commented was a couple of hours earlier that day, and is located here: https://github.com/saltstack/salt/pull/43748.

My best guess is that perhaps something in the GitHub API has changed, so that mentionbot isn't finding the diff to analyze? I am not sure. I haven't been able to narrow down why or find any announcements about the GH API changing that would affect this, but perhaps someone else more knowledgable of mention bot has some insight.

**Comment by neolit123** [comment]
we also have been experiencing the bot not working in public project, but *suddenly*, today it decided to post after a new PR. no changes have been made on our side.

can someone explain why this might happen?

**Comment by vjeux** [comment]
Sorry about that. What happened is that Github banned the bot account and I contacted their support to re-enable it, which they just did.

**Comment by neolit123** [comment]
@vjeux 
thanks a lot for the reply on this!

**Comment by neolit123** [comment]
@vjeux
hi, the bot stopped working again.
we had something like 10 PR in the past week and the bot did not post in any of them. :(

**Comment by rallytime** [comment]
This isn't working for us either. The bot never did start working for us again and I haven't seen it working since my last post, unfortunately.

**Comment by NARKOZ** [comment]
@vjeux the bot still doesn't work.

**Comment by vjeux** [comment]
Sorry about this everyone. I don't have time to maintain it. I just moved the whole repo to facebookarchive/
