### ISSUE TITLE
Blame 'none' issue

### ISSUE THREAD

**Issue by vinhlh** [facebook/mention-bot#44]
![image](https://cloud.githubusercontent.com/assets/261283/11496001/e028cf34-9841-11e5-86ea-b8c33ed9e70d.png)

In this case, the blame value always is 'none'.

Do you guys think this is a bug?
So, will I create a PR.

**Comment by vinhlh** [comment]
But there are no link, no way to get the username of the user.

**Comment by vjeux** [comment]
Good catch, I forgot that it could happen. The way it is setup right now (I updated the code recently) is that we ignore all those 'none': https://github.com/facebook/mention-bot/blob/master/mention-bot.js#L295-L297

I think it's the right behavior since the goal of this is to ping people but if there's no github username this ping won't do anything.

Let me know if you think we should change the behavior to something else, in the meantime i'm going to close the issue :)

**Comment by vinhlh** [comment]
Agree!
